[versions]
kotlin = "2.3.0"
kotlinxSerialization = "1.10.0"
kotlinxKover = "0.9.5"
kotlinxIo = "0.8.2"
junit5 = "5.14.2"
okio = "3.16.4"
ktlint = "12.3.0"
ionspinBignum = "0.3.10"

[libraries]
kotlinx-io-core = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinxIo" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit5" }
okio = { group = "com.squareup.okio", name = "okio", version.ref = "okio" }
ionspin-bignum = { group = "com.ionspin.kotlin", name = "bignum", version.ref = "ionspinBignum" }

[plugins]
kotlinxKover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kotlinxKover" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
